name: Deploy Terraform & DeepSeek Model R1

on:
  push:
    branches:
      - main  # Change to any branch if needed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Provision Infra & Deploy Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::242201266221:role/GitHubActionsTerraformRole
          role-session-name: GitHubActions
          aws-region: us-east-1  # Change to your preferred region

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Use the required Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Retrieve EC2 Public IP
        id: get-ec2-ip
        run: |
          PRIVATE_KEY=$(cat terraform-project/deepseek-ec2-key.pem)
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
          PUBLIC_IP=$(terraform output -raw ec2_public_ip) # Ensure this is set in outputs
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Wait for EC2 Instance to Be Ready
        run: sleep 60  # Wait for the instance to initialize

      - name: 🚀 SSH into EC2 and Deploy DeepSeek Model
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo docker pull deepseek-ai/deepseek-llm:latest
            sudo docker run -d --name deepseek -p 8080:8080 deepseek-ai/deepseek-llm

      - name: 🎉 Deployment Completed
        run: echo "DeepSeek Model is running at http://${{ env.PUBLIC_IP }}:8080"
 